[tool.poetry]
name = "topic-classification-vciom"
version = "0.1.0"
description = ""
authors = ["anatoly <t.vlasov23@mail.ru>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
